### ISSUE TITLE
Errors while uploading files

### ISSUE THREAD

**Issue by MeijeSibbel** [NutterzUK/storj-java-bridge-client#25]
com.sun.jersey.api.client.UniformInterfaceException: POST https://api.storj.io/frames returned a response status of 502 Bad Gateway
    at com.sun.jersey.api.client.WebResource.handle(WebResource.java:688)
    at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
    at com.sun.jersey.api.client.WebResource$Builder.post(WebResource.java:560)
    at storj.io.restclient.rest.StorjRestClient.createFrame(StorjRestClient.java:235)
    at storj.io.client.DefaultStorjClient.uploadFile(DefaultStorjClient.java:61)
    at sample.Controller$2.call(Controller.java:353)
    at sample.Controller$2.call(Controller.java:349)
    at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

Response from Server:

POST https://api.storj.io/frames returned a response status of 502 Bad Gateway

**Comment by MeijeSibbel** [comment]
The following error is persistent for all uploads of files.

com.sun.jersey.api.client.UniformInterfaceException: PUT https://api.storj.io/frames/57ced3608d8000733b7dfffd returned a response status of 500 Internal Server Error
    at com.sun.jersey.api.client.WebResource.handle(WebResource.java:688)
    at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
    at com.sun.jersey.api.client.WebResource$Builder.put(WebResource.java:529)
    at storj.io.restclient.rest.StorjRestClient.addShardToFrame(StorjRestClient.java:285)
    at storj.io.client.DefaultStorjClient.uploadFile(DefaultStorjClient.java:65)
    at sample.Controller$2.call(Controller.java:353)
    at sample.Controller$2.call(Controller.java:349)
    at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

Response from Server:

PUT https://api.storj.io/frames/57ced3608d8000733b7dfffd returned a response status of 500 Internal Server Error
